# Generated by Django 5.1.2 on 2024-11-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.IntegerField(default=1),
        ),
    ]
