# Generated by Django 5.1.2 on 2024-11-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_to_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='bankrupt', max_length=200, null=True)),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
        ),
    ]
