# Generated by Django 5.1.2 on 2024-11-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, default='bankrupt', max_length=100, null=True),
        ),
    ]
